// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkecpofrnipftwnsvyfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZWNwb2ZybmlwZnR3bnN2eWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTI2MjcsImV4cCI6MjA3MDQ4ODYyN30.2qXQeMBeMcy0yHLf3gCia2YYpbMWx2T2oNQv_9eJ8Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});